version : '3.1'

services:
 postgres_service:
  image: postgres
  restart: unless-stopped
  container_name: postgres_db_container
  ports:
   - "5433:5432"
  volumes:
   - pgdata:/pgdata
  environment:
   POSTGRES_USER: joy
   POSTGRES_DB: backend
   POSTGRES_PASSWORD: Msichana@1
  networks:
   - backend_network

 backend:
  depends_on:
   - postgres_service
  build: ./
  container_name: backend
  image: backend_container
  restart: unless-stopped
  ports:
   - "4000:4000"
  environment:
   - DB_URL=postgres_service
  networks:
   - backend_network

volumes:
 pgdata:

networks:
 backend_network:
